################################################################################
# Automatically-generated file. Do not edit!
################################################################################

SX_SRCS := 
O_SRCS := 
ASM_UPPER_SRCS_QUOTED := 
ELF_SRCS_QUOTED := 
OBJ_SRCS_OS_FORMAT := 
ELF_SRCS := 
TODISASSEMBLE_SRCS_OS_FORMAT := 
S_UPPER_SRCS_QUOTED := 
S_UPPER_SRCS := 
SX_SRCS_QUOTED := 
TODISASSEMBLE_SRCS := 
OBJ_SRCS_QUOTED := 
O_SRCS_OS_FORMAT := 
TOPREPROCESS_SRCS := 
C_SRCS_QUOTED := 
ELF_SRCS_OS_FORMAT := 
S_SRCS_OS_FORMAT := 
SX_SRCS_OS_FORMAT := 
O_SRCS_QUOTED := 
OBJ_SRCS := 
ASM_SRCS := 
TOPREPROCESS_SRCS_OS_FORMAT := 
ASM_UPPER_SRCS := 
ASM_SRCS_OS_FORMAT := 
C_SRCS := 
S_SRCS := 
ASM_SRCS_QUOTED := 
S_SRCS_QUOTED := 
TOPREPROCESS_SRCS_QUOTED := 
ASM_UPPER_SRCS_OS_FORMAT := 
C_SRCS_OS_FORMAT := 
TODISASSEMBLE_SRCS_QUOTED := 
S_UPPER_SRCS_OS_FORMAT := 
ASM_DEPS_OS_FORMAT := 
S_DEPS_QUOTED := 
OBJS := 
EXECUTABLES_OS_FORMAT := 
SECONDARY_FLASH := 
S_DEPS := 
SECONDARY_SIZE_OS_FORMAT := 
SECONDARY_LIST_QUOTED := 
SECONDARY_LIST := 
S_UPPER_DEPS := 
SECONDARY_SIZE := 
ASM_DEPS := 
SECONDARY_FLASH_QUOTED := 
OBJS_QUOTED := 
SECONDARY_LIST_OS_FORMAT := 
S_UPPER_DEPS_QUOTED := 
EXECUTABLES := 
SX_DEPS_OS_FORMAT := 
C_DEPS := 
SX_DEPS := 
ASM_DEPS_QUOTED := 
S_UPPER_DEPS_OS_FORMAT := 
SECONDARY_SIZE_QUOTED := 
S_DEPS_OS_FORMAT := 
SECONDARY_FLASH_OS_FORMAT := 
ASM_UPPER_DEPS_QUOTED := 
ASM_UPPER_DEPS := 
SX_DEPS_QUOTED := 
ASM_UPPER_DEPS_OS_FORMAT := 
C_DEPS_OS_FORMAT := 
EXECUTABLES_QUOTED := 
OBJS_OS_FORMAT := 
C_DEPS_QUOTED := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Sources \
Sources/drivers/uart \
Sources/drivers/sai \
Sources/drivers/mcg \
Sources/drivers \
Sources/drivers/adc16 \
Sources/cpu \
Sources/DSP \
Project_Settings/Startup_Code \

